let store = {
  activeInventory: "Greenhouse",
  inventoryBeingCreated: [],
  properties: {
    Greenhouse: ["Date Planted"],
    Movies: ["Genre", "Runtime (min)"],
    Garage: ["Brand", "Year", "Color"],
  },
  inventories: {
    Greenhouse: [
      {
        id: 1,
        name: "Gymnoderma Lichen",
        "Date Planted": "09/08/2020",
        qty: 20,
      },
      {
        id: 2,
        name: "River Bottlebrush",
        "Date Planted": "01/28/2021",
        qty: 17,
      },
      {
        id: 3,
        name: "Arctic Brome",
        "Date Planted": "11/12/2020",
        qty: 10,
      },
      {
        id: 4,
        name: "Toano Milkvetch",
        "Date Planted": "09/03/2020",
        qty: 20,
      },
      {
        id: 5,
        name: "Giant Cane",
        "Date Planted": "05/27/2020",
        qty: 2,
      },
      {
        id: 6,
        name: "Hawkweed",
        "Date Planted": "11/30/2020",
        qty: 7,
      },
      {
        id: 7,
        name: "Alabama Cherry",
        "Date Planted": "05/06/2020",
        qty: 15,
      },
      {
        id: 8,
        name: "Smooth Cat's Ear",
        "Date Planted": "05/02/2021",
        qty: 16,
      },
      {
        id: 9,
        name: "Twisselmann's Buckwheat",
        "Date Planted": "06/24/2021",
        qty: 13,
      },
      {
        id: 10,
        name: "Wand Buckwheat",
        "Date Planted": "05/31/2020",
        qty: 18,
      },
      {
        id: 12,
        name: "Humped Bladderwort",
        "Date Planted": "04/16/2021",
        qty: 7,
      },
      {
        id: 13,
        name: "Stebbins' Lewisia",
        "Date Planted": "11/14/2020",
        qty: 15,
      },
      {
        id: 14,
        name: "Fuzzy Dewberry",
        "Date Planted": "06/12/2021",
        qty: 16,
      },
      {
        id: 15,
        name: "Mokihana",
        "Date Planted": "07/30/2020",
        qty: 5,
      },
      {
        id: 16,
        name: "Common Yampah",
        "Date Planted": "06/27/2021",
        qty: 6,
      },
      {
        id: 17,
        name: "Kauai Nehe",
        "Date Planted": "03/13/2021",
        qty: 15,
      },
      {
        id: 18,
        name: "Owl's-claws",
        "Date Planted": "05/18/2020",
        qty: 8,
      },
      {
        id: 19,
        name: "Windmill Grass",
        "Date Planted": "11/03/2020",
        qty: 18,
      },
      {
        id: 20,
        name: "Tall Snapdragon",
        "Date Planted": "08/10/2020",
        qty: 15,
      },
      {
        id: 21,
        name: "Cissampelos",
        "Date Planted": "07/22/2020",
        qty: 18,
      },
    ],
    Movies: [
      {
        id: 1,
        name: "Employee of the Month",
        Genre: "Comedy",
        "Runtime (min)": 97,
        qty: 2,
      },
      {
        id: 2,
        name: "Streaks, The (Pregi)",
        Genre: "Drama",
        "Runtime (min)": 78,
        qty: 1,
      },
      {
        id: 3,
        name: "International House",
        Genre: "Comedy",
        "Runtime (min)": 52,
        qty: 1,
      },
      {
        id: 4,
        name: "Alvarez Kelly",
        Genre: "Western",
        "Runtime (min)": 126,
        qty: 1,
      },
      {
        id: 5,
        name: "Mission: Impossible - Ghost Protocol",
        Genre: "Action|Adventure|Thriller|IMAX",
        "Runtime (min)": 52,
        qty: 1,
      },
      {
        id: 6,
        name: "Terror of Mechagodzilla (Mekagojira no gyakushu)",
        Genre: "Action|Sci-Fi",
        "Runtime (min)": 58,
        qty: 3,
      },
      {
        id: 7,
        name: "Foolish",
        Genre: "Comedy",
        "Runtime (min)": 113,
        qty: 2,
      },
      {
        id: 8,
        name: "Bulletproof Monk",
        Genre: "Action|Adventure|Sci-Fi",
        "Runtime (min)": 135,
        qty: 1,
      },
      {
        id: 9,
        name: "High Wind in Jamaica, A",
        Genre: "Adventure|Drama",
        "Runtime (min)": 41,
        qty: 2,
      },
      {
        id: 10,
        name: "Days of Wine and Roses",
        Genre: "Drama",
        "Runtime (min)": 88,
        qty: 1,
      },
      {
        id: 11,
        name: "Missing Person, The",
        Genre: "Drama|Film-Noir|Mystery",
        "Runtime (min)": 175,
        qty: 2,
      },
      {
        id: 12,
        name: "To Kill a Priest",
        Genre: "Drama",
        "Runtime (min)": 142,
        qty: 3,
      },
      {
        id: 13,
        name: "Pursuit of Happiness",
        Genre: "Comedy|Romance",
        "Runtime (min)": 99,
        qty: 3,
      },
      {
        id: 14,
        name: "I'm Not Scared (Io non ho paura)",
        Genre: "Drama|Mystery|Thriller",
        "Runtime (min)": 180,
        qty: 1,
      },
      {
        id: 15,
        name: "Silentium",
        Genre: "Crime|Thriller",
        "Runtime (min)": 80,
        qty: 1,
      },
      {
        id: 16,
        name: "Tarzan the Ape Man",
        Genre: "Action|Adventure",
        "Runtime (min)": 55,
        qty: 3,
      },
      {
        id: 17,
        name: "Starship Troopers: Invasion",
        Genre: "Action|Animation|Sci-Fi|War",
        "Runtime (min)": 139,
        qty: 3,
      },
      {
        id: 18,
        name: "Snow Dogs",
        Genre: "Adventure|Children|Comedy",
        "Runtime (min)": 156,
        qty: 1,
      },
      {
        id: 19,
        name: "Pornstar: The Legend of Ron Jeremy",
        Genre: "Documentary",
        "Runtime (min)": 97,
        qty: 2,
      },
      {
        id: 20,
        name: "Tough Enough (Knallhart)",
        Genre: "Crime|Drama",
        "Runtime (min)": 131,
        qty: 3,
      },
    ],
    Garage: [
      {
        id: 1,
        name: "Impreza",
        Brand: "Subaru",
        Year: 2010,
        Color: "Pink",
        qty: 1,
      },
      {
        id: 2,
        name: "Mustang",
        Brand: "Ford",
        Year: 2003,
        Color: "Puce",
        qty: 1,
      },
      {
        id: 3,
        name: "RL",
        Brand: "Acura",
        Year: 2002,
        Color: "Puce",
        qty: 1,
      },
      {
        id: 4,
        name: "Excursion",
        Brand: "Ford",
        Year: 2004,
        Color: "Fuscia",
        qty: 1,
      },
      {
        id: 5,
        name: "Santa Fe",
        Brand: "Hyundai",
        Year: 2010,
        Color: "Purple",
        qty: 1,
      },
      {
        id: 6,
        name: "LS",
        Brand: "Lincoln",
        Year: 2000,
        Color: "Crimson",
        qty: 1,
      },
      {
        id: 7,
        name: "Express 1500",
        Brand: "Chevrolet",
        Year: 1997,
        Color: "Crimson",
        qty: 1,
      },
      {
        id: 8,
        name: "Lancer Evolution",
        Brand: "Mitsubishi",
        Year: 2005,
        Color: "Aquamarine",
        qty: 1,
      },
      {
        id: 9,
        name: "Galant",
        Brand: "Mitsubishi",
        Year: 2010,
        Color: "Purple",
        qty: 1,
      },
      {
        id: 10,
        name: "Astro",
        Brand: "Chevrolet",
        Year: 1999,
        Color: "Yellow",
        qty: 1,
      },
      {
        id: 11,
        name: "Monte Carlo",
        Brand: "Chevrolet",
        Year: 2002,
        Color: "Khaki",
        qty: 1,
      },
    ],
  },
};

export default { store };
